In [2]:
#http://iamtrask.github.io/2015/07/12/basic-python-network/

#2 Layer Neural Network:
import numpy as np
np.set_printoptions(suppress=True)

In [16]:
# Sigmoid and its derivative function
def nonlin(x, deriv=False):
    if (deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [17]:
# Input dataset matrix where each row is a training example
X = np.array([[0,0,1],
              [0,1,1],              
              [1,0,1],
              [1,1,1]])
type(X), X.shape

(numpy.ndarray, (4L, 3L))

In [18]:
# Output dataset matrix where each row is a training example
y = np.array([[0,0,1,1]]).T
type(y), y.shape

(numpy.ndarray, (4L, 1L))

In [19]:
# seed random numbers to make calculation deterministic (just a good practice)
np.random.seed(1)

In [20]:
# initialize weights randomly with mean 0
# Syn0 = First layer of weights, Synapse 0, connecting l0 to l1.
syn0 = 2*np.random.random((3,1)) - 1
syn0

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [21]:
iterations = 10000
for iter in xrange(iterations):
    # forward propagation    
    # L0 = First Layer of the Network, specified by the input data
    l0 = X
    
    # L1 = Second Layer of the Network, otherwise known as the hidden layer
    l1 = nonlin(np.dot(l0,syn0))
    
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)
    
    if (iter % (iterations/10) == 0):
        print "-------------------------------"
        print "Output loop ", iter, " training"
        print "-------------------------------"
        print "===============\nL0 (X)\n===============\n", l0
        print "\n===============\nsyn0 (pesos)\n===============\n", syn0
        print "\n===============\nnp.dot(L0,syn0)\n===============\n", np.dot(l0,syn0)
        print "\n===============\nL1 (Y') = sigmoide(np.dot(L0,syn0)) \n===============\n", l1
        print "\n===============\nL1 error (Y' - Y)\n===============\n", l1_error
        print "\n===============\nL1 error np.mean(np.abs(l1_error))\n===============\n", str(np.mean(np.abs(l1_error)))
        print "\n===============\nnonlin(L1, True) (slope sigmóide de L1)\n===============\n", nonlin(l1, True)
        print "\n===============\nL1 delta = (L1 error * slope sigmóide de L1)\n===============\n", l1_delta
        print "\n===============\nL0 transposto\n===============\n", l0.T
        print "\n===============\nnp.dot(L0.T, l1_delta) para somar a syn0\n===============\n", np.dot(l0.T, l1_delta)
        print "\n===============\nold syn0\n===============\n", syn0
    # update weights
    syn0 += np.dot(l0.T, l1_delta)   
    
    if (iter % (iterations/10) == 0):        
        print "\n===============\nnew syn0\n===============\n", syn0
        
print "\n===============\nOutput after training\n===============\n", l1
print "\n===============\nFinal syn0\n===============\n", syn0

-------------------------------
Output loop  0  training
-------------------------------
L0 (X)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

syn0 (pesos)
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

np.dot(L0,syn0)
[[-0.99977125]
 [-0.55912226]
 [-1.16572724]
 [-0.72507825]]

L1 (Y') = sigmoide(np.dot(L0,syn0)) 
[[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]

L1 error (Y' - Y)
[[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]

L1 error np.mean(np.abs(l1_error))
0.517208275438

nonlin(L1, True) (slope sigmóide de L1)
[[ 0.19663272]
 [ 0.23143609]
 [ 0.18116102]
 [ 0.21981987]]

L1 delta = (L1 error * slope sigmóide de L1)
[[-0.05289153]
 [-0.08418501]
 [ 0.13811206]
 [ 0.14809799]]

L0 transposto
[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]

np.dot(L0.T, l1_delta) para somar a syn0
[[ 0.28621005]
 [ 0.06391297]
 [ 0.14913351]]

old syn0
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

new syn0
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
-------------------------------
Output lo


L1 (Y') = sigmoide(np.dot(L0,syn0)) 
[[ 0.18557542]
 [ 0.16861163]
 [ 0.86281329]
 [ 0.84843474]]

L1 error (Y' - Y)
[[-0.18557542]
 [-0.16861163]
 [ 0.13718671]
 [ 0.15156526]]

L1 error np.mean(np.abs(l1_error))
0.160734754179

nonlin(L1, True) (slope sigmóide de L1)
[[ 0.15113718]
 [ 0.14018175]
 [ 0.11836652]
 [ 0.12859323]]

L1 delta = (L1 error * slope sigmóide de L1)
[[-0.02804735]
 [-0.02363627]
 [ 0.01623831]
 [ 0.01949027]]

L0 transposto
[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]

np.dot(L0.T, l1_delta) para somar a syn0
[[ 0.03572858]
 [-0.00414601]
 [-0.01595504]]

old syn0
[[ 3.31787592]
 [-0.11647855]
 [-1.47902048]]

new syn0
[[ 3.3536045 ]
 [-0.12062456]
 [-1.49497552]]
-------------------------------
Output loop  37  training
-------------------------------
L0 (X)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

syn0 (pesos)
[[ 3.3536045 ]
 [-0.12062456]
 [-1.49497552]]

np.dot(L0,syn0)
[[-1.49497552]
 [-1.61560008]
 [ 1.85862898]
 [ 1.73800442]]

L1 (Y') = sigmoide(np.dot(L0,syn0)) 
[[

In [204]:
# Testing our predictor
X_test = np.array([[1,1,1],
                   [0,0,0]])
X_test

array([[1, 1, 1],
       [0, 0, 0]])

In [139]:
# Prediction
Y_test = nonlin(np.dot(X_test,syn0))
Y_test

array([[ 0.99211997],
       [ 0.5       ]])