In [41]:
#http://iamtrask.github.io/2015/07/12/basic-python-network/

#2 Layer Neural Network:
import numpy as np

In [42]:
# sigmoid function
def nonlin(x, deriv=False):
    if (deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [43]:
# Input dataset matrix where each row is a training example
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

In [44]:
type(X), X.shape

(numpy.ndarray, (4L, 3L))

In [45]:
# Output dataset matrix where each row is a training example
y = np.array([[0,0,1,1]]).T

In [46]:
type(y), y.shape

(numpy.ndarray, (4L, 1L))

In [47]:
# seed random numbers to make calculation deterministic (just a good practice)
np.random.seed(1)

In [48]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

In [49]:
# Syn0 = First layer of weights, Synapse 0, connecting l0 to l1.
syn0

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [60]:
for iter in xrange(10000):
    # forward propagation
    
    #L0 = First Layer of the Network, specified by the input data
    l0 = X
    
    # L1 = Second Layer of the Network, otherwise known as the hidden layer
    l1 = nonlin(np.dot(l0,syn0))
    if (iter % 1000 == 0):
        print "-------------------------------"
        print "Output loop ", iter, " training"
        print "-------------------------------"
        print "syn0: \n", syn0
        print "L1: \n",l1
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)
    
    # update weights
    syn0 += np.dot(l0.T, l1_delta)   
    
print "Output after training"
print l1

-------------------------------
Output loop  0  training
-------------------------------
syn0: 
[[ 12.00870061]
 [ -0.2044116 ]
 [ -5.8002822 ]]
L1: 
[[ 0.00301757]
 [ 0.00246107]
 [ 0.99799162]
 [ 0.99753724]]
-------------------------------
Output loop  1000  training
-------------------------------
syn0: 
[[ 12.01872615]
 [ -0.20440338]
 [ -5.80530155]]
L1: 
[[ 0.0030025 ]
 [ 0.0024488 ]
 [ 0.99800163]
 [ 0.99754953]]
-------------------------------
Output loop  2000  training
-------------------------------
syn0: 
[[ 12.02865254]
 [ -0.20439528]
 [ -5.81027122]]
L1: 
[[ 0.00298766]
 [ 0.00243671]
 [ 0.99801149]
 [ 0.99756163]]
-------------------------------
Output loop  3000  training
-------------------------------
syn0: 
[[ 12.03848172]
 [ -0.20438731]
 [ -5.8151922 ]]
L1: 
[[ 0.00297304]
 [ 0.0024248 ]
 [ 0.99802121]
 [ 0.99757356]]
-------------------------------
Output loop  4000  training
-------------------------------
syn0: 
[[ 12.04821558]
 [ -0.20437944]
 [ -5.82006542]]

In [38]:
# X: Input dataset matrix where each row is a training example
# y: Output dataset matrix where each row is a training example
# l0: First Layer of the Network, specified by the input data
# l1: Second Layer of the Network, otherwise known as the hidden layer
# syn0: First layer of weights, Synapse 0, connecting l0 to l1.
# *: Elementwise multiplication, so two vectors of equal size are multiplying corresponding values 1-to-1 to generate a final vector of identical size.
# -: Elementwise subtraction, so two vectors of equal size are subtracting corresponding values 1-to-1 to generate a final vector of identical size.
# x.dot(y): If x and y are vectors, this is a dot product. 
#           If both are matrices, it's a matrix-matrix multiplication. 
#           If only one is a matrix, then it's vector matrix multiplication.