In [2]:
#http://iamtrask.github.io/2015/07/12/basic-python-network/

#2 Layer Neural Network:
import numpy as np
np.set_printoptions(suppress=True)

In [16]:
# Sigmoid and its derivative function
def nonlin(x, deriv=False):
    if (deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [17]:
# Input dataset matrix where each row is a training example
X = np.array([[0,0,1],
              [0,1,1],              
              [1,0,1],
              [1,1,1]])
type(X), X.shape

(numpy.ndarray, (4L, 3L))

In [18]:
# Output dataset matrix where each row is a training example
y = np.array([[0,0,1,1]]).T
type(y), y.shape

(numpy.ndarray, (4L, 1L))

In [19]:
# seed random numbers to make calculation deterministic (just a good practice)
np.random.seed(1)

In [20]:
# initialize weights randomly with mean 0
# Syn0 = First layer of weights, Synapse 0, connecting l0 to l1.
syn0 = 2*np.random.random((3,1)) - 1
syn0

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [22]:
iterations = 10000
for iter in xrange(iterations):
    # forward propagation    
    # L0 = First Layer of the Network, specified by the input data
    l0 = X
    
    # L1 = Second Layer of the Network, otherwise known as the hidden layer
    l1 = nonlin(np.dot(l0,syn0))
    
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)
    
    if (iter % (iterations/10) == 0):
        print "-------------------------------"
        print "Output loop ", iter, " training"
        print "-------------------------------"
        print "===============\nL0 (X)\n===============\n", l0
        print "\n===============\nsyn0 (pesos)\n===============\n", syn0
        print "\n===============\nnp.dot(L0,syn0)\n===============\n", np.dot(l0,syn0)
        print "\n===============\nL1 (Y') = sigmoide(np.dot(L0,syn0)) \n===============\n", l1
        print "\n===============\nL1 error (Y' - Y)\n===============\n", l1_error
        print "\n===============\nL1 error np.mean(np.abs(l1_error))\n===============\n", str(np.mean(np.abs(l1_error)))
        print "\n===============\nnonlin(L1, True) (slope sigmóide de L1)\n===============\n", nonlin(l1, True)
        print "\n===============\nL1 delta = (L1 error * slope sigmóide de L1)\n===============\n", l1_delta
        print "\n===============\nL0 transposto\n===============\n", l0.T
        print "\n===============\nnp.dot(L0.T, l1_delta) para somar a syn0\n===============\n", np.dot(l0.T, l1_delta)
        print "\n===============\nold syn0\n===============\n", syn0
    # update weights
    syn0 += np.dot(l0.T, l1_delta)   
    
    if (iter % (iterations/10) == 0):        
        print "\n===============\nnew syn0\n===============\n", syn0
        
print "\n===============\nOutput after training\n===============\n", l1
print "\n===============\nFinal syn0\n===============\n", syn0

-------------------------------
Output loop  0  training
-------------------------------
L0 (X)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

syn0 (pesos)
[[ 3.45516399]
 [-0.13171941]
 [-1.54066892]]

np.dot(L0,syn0)
[[-1.54066892]
 [-1.67238832]
 [ 1.91449507]
 [ 1.78277566]]

L1 (Y') = sigmoide(np.dot(L0,syn0)) 
[[ 0.17643806]
 [ 0.15810601]
 [ 0.8715233 ]
 [ 0.85603927]]

L1 error (Y' - Y)
[[-0.17643806]
 [-0.15810601]
 [ 0.1284767 ]
 [ 0.14396073]]

L1 error np.mean(np.abs(l1_error))
0.151745374638

nonlin(L1, True) (slope sigmóide de L1)
[[ 0.14530767]
 [ 0.1331085 ]
 [ 0.11197043]
 [ 0.12323604]]

L1 delta = (L1 error * slope sigmóide de L1)
[[-0.0256378 ]
 [-0.02104525]
 [ 0.01438559]
 [ 0.01774115]]

L0 transposto
[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]

np.dot(L0.T, l1_delta) para somar a syn0
[[ 0.03212674]
 [-0.0033041 ]
 [-0.01455631]]

old syn0
[[ 3.45516399]
 [-0.13171941]
 [-1.54066892]]

new syn0
[[ 3.48729073]
 [-0.13502351]
 [-1.55522523]]
-------------------------------
Output lo

-------------------------------
Output loop  7000  training
-------------------------------
L0 (X)
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]

syn0 (pesos)
[[ 9.31261859]
 [-0.20874679]
 [-4.44869607]]

np.dot(L0,syn0)
[[-4.44869607]
 [-4.65744286]
 [ 4.86392251]
 [ 4.65517572]]

L1 (Y') = sigmoide(np.dot(L0,syn0)) 
[[ 0.01155864]
 [ 0.00940147]
 [ 0.992339  ]
 [ 0.99057739]]

L1 error (Y' - Y)
[[-0.01155864]
 [-0.00940147]
 [ 0.007661  ]
 [ 0.00942261]]

L1 error np.mean(np.abs(l1_error))
0.0095109309416

nonlin(L1, True) (slope sigmóide de L1)
[[ 0.01142504]
 [ 0.00931309]
 [ 0.00760231]
 [ 0.00933383]]

L1 delta = (L1 error * slope sigmóide de L1)
[[-0.00013206]
 [-0.00008756]
 [ 0.00005824]
 [ 0.00008795]]

L0 transposto
[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]

np.dot(L0.T, l1_delta) para somar a syn0
[[ 0.00014619]
 [ 0.00000039]
 [-0.00007342]]

old syn0
[[ 9.31261859]
 [-0.20874679]
 [-4.44869607]]

new syn0
[[ 9.31276478]
 [-0.2087464 ]
 [-4.4487695 ]]
-------------------------------
Outpu

In [204]:
# Testing our predictor
X_test = np.array([[1,1,1],
                   [0,0,0]])
X_test

array([[1, 1, 1],
       [0, 0, 0]])

In [139]:
# Prediction
Y_test = nonlin(np.dot(X_test,syn0))
Y_test

array([[ 0.99211997],
       [ 0.5       ]])