In [27]:
#http://iamtrask.github.io/2015/07/12/basic-python-network/

#3 Layer Neural Network:
import numpy as np
np.set_printoptions(suppress=True)

In [28]:
def nonlin(x, deriv=False):
    if (deriv == True):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

In [29]:
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1],
              [0,0,0],
              [0,1,0],
              [1,0,0],
              [1,1,0],])
y = np.array([[0],[1],[1],[0],[0],[1],[1],[0]])

In [30]:
np.random.seed(1)

In [31]:
# randomly initialize our weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [32]:
for j in xrange(60000):
    # Feed forward through layers 0, 1 and 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    # how much did we miss the target value?
    l2_error = y - l2
    
    if (j%10000 == 0):
        print "Error:" + str(np.mean(np.abs(l2_error)))
    
    # in what direction is the target value?
    # were we really sure? if so, don't change too much
    l2_delta = l2_error * nonlin(l2, deriv=True)
    
    # how much did each l1 value contribute to the l2 error (according to the weights) ?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much
    l1_delta = l1_error * nonlin(l1, deriv=True)
    
    #updating weights
    syn1 += l1.T.dot(l2_delta)    
    syn0 += l0.T.dot(l1_delta)
    
print "\n===============\nOutput after training\n===============\n", l2
print "\n===============\nFinal syn0\n===============\n", syn0
print "\n===============\nFinal syn1\n===============\n", syn1

Error:0.496594645572
Error:0.0111573958914
Error:0.00777321739466
Error:0.00631010429369
Error:0.00544704547599
Error:0.00486166387165

Output after training
[[ 0.00069079]
 [ 0.9956045 ]
 [ 0.99494822]
 [ 0.00397855]
 [ 0.00805094]
 [ 0.99525902]
 [ 0.99506009]
 [ 0.0036024 ]]

Final syn0
[[ 5.82600887  4.23467033 -6.42928367 -6.91049885]
 [-2.72826627 -8.33613644 -6.24449123  3.39964891]
 [-0.32518005 -0.01987913  0.57714751  0.0333551 ]]

Final syn1
[[ -6.25679349]
 [ 11.73947778]
 [-21.07152648]
 [  5.96106074]]
