In [146]:
#http://iamtrask.github.io/2015/07/12/basic-python-network/

#2 Layer Neural Network:
import numpy as np

In [147]:
# sigmoid function
def nonlin(x, deriv=False):
    if (deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [148]:
# Input dataset matrix where each row is a training example
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

In [149]:
type(X), X.shape

(numpy.ndarray, (4L, 3L))

In [150]:
# Output dataset matrix where each row is a training example
y = np.array([[0,0,1,1]]).T

In [151]:
type(y), y.shape

(numpy.ndarray, (4L, 1L))

In [152]:
# seed random numbers to make calculation deterministic (just a good practice)
np.random.seed(1)

In [153]:
# initialize weights randomly with mean 0
# Syn0 = First layer of weights, Synapse 0, connecting l0 to l1.
syn0 = 2*np.random.random((3,1)) - 1

In [155]:
for iter in xrange(10000):
    # forward propagation
    
    #L0 = First Layer of the Network, specified by the input data
    l0 = X
    
    # L1 = Second Layer of the Network, otherwise known as the hidden layer
    l1 = nonlin(np.dot(l0,syn0))
    
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)
    
    if (iter % 1000 == 0):
        print "-------------------------------"
        print "Output loop ", iter, " training"
        print "-------------------------------"
        print "===============\nsyn0\n===============\n", syn0
        print "\n===============\nL1\n===============\n", l1
        print "\n===============\nL1 error\n===============\n", l1_error
        print "\n===============\nL1 delta\n===============\n", l1_delta
        print "\n===============\nnonlin(l1, True)\n===============\n", nonlin(l1, True)
            
    # update weights
    syn0 += np.dot(l0.T, l1_delta)   
    
    if (iter % 1000 == 0):        
        print "\n===============\nnew syn0\n===============\n", syn0
        
print "Output after training"
print l1

-------------------------------
Output loop  0  training
-------------------------------
syn0
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]

L1
[[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]

L1 error
[[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]

L1 delta
[[-0.05289153]
 [-0.08418501]
 [ 0.13811206]
 [ 0.14809799]]

nonlin(l1, True)
[[ 0.19663272]
 [ 0.23143609]
 [ 0.18116102]
 [ 0.21981987]]

new syn0
[[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
-------------------------------
Output loop  1000  training
-------------------------------
syn0
[[ 7.26283009]
 [-0.21614618]
 [-3.41703015]]

L1
[[ 0.03176745]
 [ 0.02575143]
 [ 0.97907779]
 [ 0.97416005]]

L1 error
[[-0.03176745]
 [-0.02575143]
 [ 0.02092221]
 [ 0.02583995]]

L1 delta
[[-0.00097711]
 [-0.00064606]
 [ 0.00042858]
 [ 0.00065045]]

nonlin(l1, True)
[[ 0.03075828]
 [ 0.02508829]
 [ 0.02048447]
 [ 0.02517225]]

new syn0
[[ 7.26390912]
 [-0.21614179]
 [-3.41757429]]
-------------------------------
O

In [38]:
# X: Input dataset matrix where each row is a training example
# y: Output dataset matrix where each row is a training example
# l0: First Layer of the Network, specified by the input data
# l1: Second Layer of the Network, otherwise known as the hidden layer
# syn0: First layer of weights, Synapse 0, connecting l0 to l1.
# *: Elementwise multiplication, so two vectors of equal size are multiplying corresponding values 1-to-1 to generate a final vector of identical size.
# -: Elementwise subtraction, so two vectors of equal size are subtracting corresponding values 1-to-1 to generate a final vector of identical size.
# x.dot(y): If x and y are vectors, this is a dot product. 
#           If both are matrices, it's a matrix-matrix multiplication. 
#           If only one is a matrix, then it's vector matrix multiplication.