In [3]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree

iris = load_iris()

In [4]:
print "\niris.feature_names"
print iris.feature_names

print "\niris.target_names"
print iris.target_names


iris.feature_names
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

iris.target_names
['setosa' 'versicolor' 'virginica']


In [5]:
print "\niris.data[0]"
print iris.data[0]

print "\niris.target[0]"
print iris.target[0]

print "\niris.target_names[iris.target[0]]"
print iris.target_names[iris.target[0]]


iris.data[0]
[ 5.1  3.5  1.4  0.2]

iris.target[0]
0

iris.target_names[iris.target[0]]
setosa


In [6]:
# iterating over the 150 rows

#for i in range(len(iris.target)):
#	print "Example %d: label %s, features %s" % (i, iris.target[i], iris.data[i])

# remove one example of each type of flower
test_idx = [0, 50, 100] # setosa, versicolor and so on

# training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

print "\ntype(train_target)"
print type(train_target)
print "\ntrain_target.shape"
print train_target.shape
print "\ntype(train_data)"
print type(train_data)
print "\ntrain_data.shape"
print train_data.shape

print "\ntype(test_target)"
print type(test_target)
print "\ntest_target.shape"
print test_target.shape
print "\ntype(test_data)"
print type(test_data)
print "\ntest_data.shape"
print test_data.shape


type(train_target)
<type 'numpy.ndarray'>

train_target.shape
(147L,)

type(train_data)
<type 'numpy.ndarray'>

train_data.shape
(147L, 4L)

type(test_target)
<type 'numpy.ndarray'>

test_target.shape
(3L,)

type(test_data)
<type 'numpy.ndarray'>

test_data.shape
(3L, 4L)


In [13]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print(test_data)
test = [[5.3,6.5,2.4,1.2]]

print "\nActual Answer for test_data: ", test_target
print "Decision Tree predicts: ", clf.predict(test)
print "Decision Tree accuracy: ", clf.score(test_data, test_target)

import pickle
filename = 'finalized_model.sav'
pickle.dump(clf, open(filename, 'wb'))

[[ 5.1  3.5  1.4  0.2]
 [ 7.   3.2  4.7  1.4]
 [ 6.3  3.3  6.   2.5]]

Actual Answer for test_data:  [0 1 2]
Decision Tree predicts:  [0]
Decision Tree accuracy:  1.0
