In [106]:
import numpy as np

In [107]:
# Basic Slicing and Indexing
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110])

In [108]:
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [109]:
x[2:10:2] #starting from >= array[2] (30) until < array[10] (110), stepping 2 positions

array([30, 50, 70, 90])

In [110]:
# All these has the same output result
# x[2:10] 
# x[2:10:]
x[2:10:1]

array([ 30,  40,  50,  60,  70,  80,  90, 100])

In [111]:
# Negative i and j are interpreted as n + i and n + j where n is the number of elements in the corresponding dimension. 
# i = -5 => n + (-5) => 11 - 5 => 6 => x[6] = 70
# j = -1 => n + (-1) => 11 - 1 => 10 => x[10] = 100

# x[-5] = 70 (inclusive)
# x[-1] = 110 (exclusive)

x[-5:-1:1]

array([ 70,  80,  90, 100])

In [112]:
# Negative k makes stepping go towards smaller indices.
# i = -1 => n + (-1) => 11 - 1 => 10 => x[10] = 100
# j = -5 => n + (-5) => 11 - 5 => 6 => x[6] = 70

# x[-1] = 110 (inclusive)
# x[-5] = 70 (exclusive)

x[-1:-5:-1]

array([110, 100,  90,  80])

In [113]:
# From x[1] (20) until the end
x[2:]

array([ 30,  40,  50,  60,  70,  80,  90, 100, 110])

In [117]:
# From the beginning until < x[10] = 110
x[:10]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [122]:
# From the beginning until (exclusive) the last - 3
x[:-3]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [123]:
# From the last - 3 (inclusive) until the last
x[-3:]

array([ 90, 100, 110])